name: GitHub Actions Demo
run-name: Github is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run:  printenv
      - name: Access the event names
        run:  
         echo " this was triggered by event name ${{ github.event_name }}"
         echo " Triggered branch ${{ github.ref_name }}"
